### ISSUE TITLE
Allow multiple threads of CSS processing (JS as well) for WP Admin

### ISSUE THREAD

**Issue by pkostadinov90** [DevriX/DX-Starter#29]
It would be very useful to support out-of-the-box admin styles minification and processing. Right now if you need to compile a second file other than `master.css`, you need to add multiple lines. Same for the JS compilation.

Here is an example of what needs to be added for a second thread of css minification and prefixing:

```
gulp.task("admin-cssmin", function() {
	return gulp
	.src(paths.destination.css + "admin-style.css")
	.pipe(sourcemaps.init({ loadMaps: true }))
	.pipe(cleanCSS({compatibility: 'ie8'}))
	.pipe(rename({ suffix: ".min" }))
	.pipe(sourcemaps.write('./'))
	.pipe(gulp.dest(paths.destination.css))
	.pipe(notify({ message: "Successfully minified admin-styles.min.css",onLast: true }))
});

...

// The files to be watched for minifying. If more dev js files are added this
// will have to be updated.
gulp.task("watch", function() {
	...
	gulp.watch(paths.destination.css + "admin-style.css", gulp.series("admin-cssmin"));
});

...

// What will be run with simply writing "$ gulp"
gulp.task("default",
	gulp.series("sass",
		gulp.parallel(
			"minifyScripts",
			"cssmin",
			"admin-cssmin",
			"optimizeImages"
		),
		"watch"
	)
);
```

**Comment by xavortm** [comment]
@pkostadinov90 thanks for the suggestion, feel free to post a PR 👍 I only didn't find which bit is related to the _"Right now if you need to compile a second file other than master.css, you need to add multiple lines."_. The script watches for any file that doesn't use the `_` prefix and compiles it

**Comment by xavortm** [comment]
Closing this ticket as it's outdated and with low probability of resolution
