### ISSUE TITLE
Need to update README file.

### ISSUE THREAD

**Issue by mariyan-dimitrov** [DevriX/DX-Starter#30]
Hey @xavortm,
I was following the instructions in the README file and in section **Updating installed Node.js is trough NPM:** I encountered a command  (_sudo npm cache clean -f_) which I need to run in my console. 
After doing that, I received an error with the following message:
_/usr/bin/env: ‘node’: No such file or directory_
Also, there is a typo in the naming of the section.
Best Regards!

**Comment by xavortm** [comment]
Duplicate of #5
